import { Types } from "mongoose";
import { IUserInterface } from "../user/user.interface";

export interface IRoleInterface {
  _id?: any;
  role_name: string;
  role_publisher_id: Types.ObjectId | IUserInterface;
  role_updated_by?: Types.ObjectId | IUserInterface;
  dashboard_show: true | false;
  category_post: true | false;
  category_patch: true | false;
  brand_post: true | false;
  brand_patch: true | false;
  unit_dashboard_show: true | false;
  unit_post: true | false;
  unit_patch: true | false;
  site_setting_patch: true | false;
  user_post: true | false;
  user_patch: true | false;
  user_dashboard_show: true | false;
  role_post: true | false;
  role_patch: true | false;
  sale_target_post: true | false;
  sale_target_patch: true | false;
  supplier_dashboard_show: true | false;
  supplier_post: true | false;
  supplier_patch: true | false;
  supplier_payment_post: true | false;
  supplier_payment_patch: true | false;
  supplier_paid_payment_show: true | false;
  supplier_unpaid_payment_show: true | false;
  supplier_check_or_cash_out_payment_show: true | false;
  supplier_payment_dashboard_show: true | false;
  cash_patch: true | false;
  bank_dashboard_show: true | false;
  bank_post: true | false;
  bank_patch: true | false;
  customer_dashboard_show: true | false;
  customer_post: true | false;
  customer_patch: true | false;
  check_dashboard_show: true | false;
  customer_ar_show: true | false;
  check_today_dashboard_show: true | false;
  check_due_dashboard_show: true | false;
  check_or_cash_in_payment_show: true | false;
  product_post: true | false;
  product_patch: true | false;
  product_dashboard_show: true | false;
  stock_post: true | false;
  stock_ap_show: true | false;
  expense_show: true | false;
  expense_post: true | false;
  income_show: true | false;
  order_post: true | false;
  order_patch: true | false;
  order_dashboard_show: true | false;
  profit_show: true | false;
  management_order_show: true | false;
  account_order_show: true | false;
  warehouse_order_show: true | false;
  out_of_warehouse_order_show: true | false;
  ledger_show: true | false;
  order_invoice_print: true | false;
  order_challan_print: true | false;
}
